language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
env:
  global:
    secure: lEciPpxtQUH4EIXuCvDTKw1QVSiH61NKjSqsBlYTGnop2jwrIe4TNoXD9kbMOcIjUyJ3iW9xJaRMm+VQX/X3AYbb570ZmrFeB4eDJfoFYJq0Ivy961tJ5Z7CpXZf02hdujj4NMcXAvax7JUj6AfMisu53lYZhHs5mXRFZHG8RDOzpn4v5dLn1VOG5IpiqQq4XgMeYlX7aFUk5XmFgqSLDpuZeE7YHs/HqFcT3f7C8LhkbiqFITJwf+NbaRBtauqT82qpzuboDPDdXfgQXtDctW0IXU6Sey+sRzlsxShVd1cAO/7GMkUEOeqNUlRb3HV81ZgDx8KJV/33RmMPbjHazgfOdTAbTGOyUUEmj4optWLf7tWaF8CnHNyWtwN63cou7uBl4HgtGYBLdns76wEpbfD6oKLllwO4+aM/Gix2ffQ3673rDymoK2r217gly82UZlO2o3xQUgf4+VQEGLx7fI5nffw3oEm1QWPz+TD5hW+n8QXkfzJYfD0qk0XfBqlExs/4nxQP77zKJokkE/ryp9gjSiJMEWfn/e08vS/BC4nti6eLY8aAyGdeRVetJOEsWvNrvc7TXKKroIZWy7svGXPfHijcA8zOPfKOaW3IL3i7/bw+h1w6c0ijP5L3LIipTDKTQw+/x0wtRu8nUI9j557I4zjNcMeKRuhNzizXBA0=
services:
- mongodb
before_install:
- npm install webpack -g
install:
- npm install
- npm run build
before_script:
script:
- npm run dev:lint
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: hdQwsRqYsmUS02eEVAWSTuqwqwo77sAKkG76lyYIDeTgjL0QvMHtxea6SnHz4llX1ouMVCz6Zf5dlBufPZLP6NMbTpShkkCLN43nzy4kp4w5pdCh3RdAHBk/lnkVEQVCjF28J+kZj/pAdVUE93ws+Bp5GgCXL1U7EJSk+qc8ARizwVCgGRJYfBxh/g01JFngiL7YlBYzL9YsnjfMnZWu9/xt1DkFUfPebmOg6HvXfG48kB0/Gq1PTxkzcWC55AwGG4YJf0ElwpXTI10lEeHO7zgnXhLUbfAuNRWdAkh8Wr8YVTiqFbgritNoAUDa+7hakld8oPWWlejbS48FqAe3iTFQV6VzgCGntYuaWVfkyw3Bj28+ZZv3PiZ9wOLNl2kxgNEe+0TUc87HYQLboHsbznqYzfZFgZYXOZwiRqEUbPP+PEN6x5hR/0xP/T5ZfGvs9BuAF6NvksbIY8w271gU29/VBaEllaedzF1RNxG93NfgcR+DZKHbmM312D7ZNRoe6zNxtir5iGyYb18K46MHCYT5TPDunqEnr3c5qY1NobzE+KEUToHzqfEIb3Byollr03rdZsMVA7zsu0zJaPrCAiYr2iugWsJGNmWwKgG3SrHSwl1YegMjFFFegNsFoIQ7H/D+aArMAryJEltNhaIuGjO+I4AcPu/LQ68J30WsBow=
  app: young-savannah-99031
after_deploy:
