language: node_js
node_js:
- 4
notifications:
  email:
    recipients:
    - adamestela@gmail.com
branchs:
  only:
  - master
env:
  global:
    secure: lEciPpxtQUH4EIXuCvDTKw1QVSiH61NKjSqsBlYTGnop2jwrIe4TNoXD9kbMOcIjUyJ3iW9xJaRMm+VQX/X3AYbb570ZmrFeB4eDJfoFYJq0Ivy961tJ5Z7CpXZf02hdujj4NMcXAvax7JUj6AfMisu53lYZhHs5mXRFZHG8RDOzpn4v5dLn1VOG5IpiqQq4XgMeYlX7aFUk5XmFgqSLDpuZeE7YHs/HqFcT3f7C8LhkbiqFITJwf+NbaRBtauqT82qpzuboDPDdXfgQXtDctW0IXU6Sey+sRzlsxShVd1cAO/7GMkUEOeqNUlRb3HV81ZgDx8KJV/33RmMPbjHazgfOdTAbTGOyUUEmj4optWLf7tWaF8CnHNyWtwN63cou7uBl4HgtGYBLdns76wEpbfD6oKLllwO4+aM/Gix2ffQ3673rDymoK2r217gly82UZlO2o3xQUgf4+VQEGLx7fI5nffw3oEm1QWPz+TD5hW+n8QXkfzJYfD0qk0XfBqlExs/4nxQP77zKJokkE/ryp9gjSiJMEWfn/e08vS/BC4nti6eLY8aAyGdeRVetJOEsWvNrvc7TXKKroIZWy7svGXPfHijcA8zOPfKOaW3IL3i7/bw+h1w6c0ijP5L3LIipTDKTQw+/x0wtRu8nUI9j557I4zjNcMeKRuhNzizXBA0=
services:
- mongodb
before_install:
install:
- npm install
before_script:
script:
- npm run test
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: heroku
  api_key:
    secure: WenDKw75a7vmznZCD4F7LuTORBdJJt3JNOhtjrBgtRZ1MCdTXWOCzFycSon5yCOt/3uP0qcGrAwwFlqk0uJVSHsDr+6/W+wk7YE0poCRUIhThIkLxgZ7ni3Ob34Ofb71nNBvmux6Iq0jFQxVHgzhBLutXs9O5yHhkCn7lrTkIiTVgpIHb14Ni/UIWocZ0sUGj1bQ9SGHcotTxX5QaJXHiAkgjKtrOK6si6yMAGDDtZFwiMTLeqPG4j2VL5KmMXJl2zgcamNXO9yV2PavICQwW1mxEByGM997NgBaPrHXsF4R8dJRzf1RqHpw713K6VR6upk7a5Y5fU6+LzN8DYW66xWn6w3oiBwChvexzbGN1VumXTFkBj/Cmm+x9XVPH1UGJqXeZcPyDg5VeKIdiFR6s1dhetg1LjpdUPx8RVFkjRkF2MBq5RQr4C44KAPAWLMsyt8TdiUUB0Lxwe5u7q0o693+PRI82Farf+AvuuUJPMnBS1EDgaqVjyXDQ35ijmWB1TzrJTZdS1zMOnQwEA7Xel3K7jQm9gmbdy4sUSlrGKe/Y5j4s01eiEuV6DcnQu+f+prEPNXlD1QeXfh9wAS1AdllboIRX9aSHfyFH9+gu97ENytKfzzDmSAKFFgpYqoSGviuvnFJtyyBR3doWiNc8kz3j/4aAE/CQQnapRNocOY=
  app: kimbyarting
after_deploy:
